name: "Documentation generator"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      - name: Run generator script
        run: npm run docs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "DOCS: Update README with latest API documentation"
            git push
          fi
