name: "Documentation generator"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      - name: Run generator script
        run: npm run docs

      - name: Switch to docs branch
        run: |
          git fetch origin docs
          git checkout -B docs origin/docs
      
      - name: Replace with new docs
        run: |
          cd website
          find docs/endpoints -type f -name "*.mdx" -delete
          find docs/endpoints -type f -name "*.md" -delete
          mv ../generated-docs/*.mdx docs/endpoints/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git -C website add -A docs/endpoints

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "DOCS: Update documentation with latest API changes"
            git push origin docs
          fi
